name: Plasmoid Build Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Allow manual triggering
  workflow_dispatch:

jobs:
  build:
    name: Build and Test Plasmoid
    runs-on: ubuntu-latest
    container:
      image: kdeneon/plasma:user
      options: --user root
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y \
            build-essential \
            cmake \
            extra-cmake-modules \
            gettext \
            libkf6plasma-dev \
            pkg-kde-tools \
            qt6-base-dev \
            qt6-declarative-dev \
            qml6-module-qtqml \
            qml6-module-qtquick \
            qml6-module-qtquick-controls \
            qml6-module-qtquick-layouts \
            qml6-module-qt5compat-graphicaleffects \
            qml6-module-org-kde-kirigami \
            qml6-module-qt-labs-platform \
            kpackagetool6

      - name: Install Plasmoid
        run: |
          mkdir -p /tmp/plasma-test
          export KDEHOME=/tmp/plasma-test
          
          kpackagetool6 --type=Plasma/Applet --install .
          
          if [ $? -ne 0 ]; then
            echo "Error: Plasmoid installation failed"
            exit 1
          fi
          echo "✓ Plasmoid installed successfully"

      - name: List installed plasmoids
        run: |
          export KDEHOME=/tmp/plasma-test
          kpackagetool6 --type=Plasma/Applet --list | grep com.github.revianlabs.razermousebatteryplasmoid
          echo "✓ Plasmoid is listed among installed plasmoids"

      - name: Uninstall Plasmoid
        run: |
          export KDEHOME=/tmp/plasma-test
          kpackagetool6 --type=Plasma/Applet --remove com.github.revianlabs.razermousebatteryplasmoid
          if [ $? -ne 0 ]; then
            echo "Error: Plasmoid uninstallation failed"
            exit 1
          fi
          echo "✓ Plasmoid uninstalled successfully"
