name: Release

on:
  push:
    branches: [ "main" ]
  # Allow manual triggering
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Zip
        run: sudo apt install zip unzip

      - name: Package Plasmoid
        run: |
          cd $GITHUB_WORKSPACE/package
          zip -r razer-mouse-battery.plasmoid ./*
          cp razer-mouse-battery.plasmoid ../

      - name: Automatic Releases
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Create Release"
          files: razer-mouse-battery.plasmoid